name: Lint

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run eslint with reviewdog
        uses: reviewdog/action-eslint@v1.33.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: 'src/'
