name: Test

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  jest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: '.node-version'

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4.2.0
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Cache video for testing
        id: cache-avsynctest-vga-1m
        uses: actions/cache@v4.2.0
        with:
          path: videos/avsynctest-vga-1m.mp4
          key: avsynctest-vga-1m

      - name: Generate video for testing
        if: steps.cache-avsynctest-vga-1m.outputs.cache-hit != 'true'
        run: make videos/avsynctest-vga-1m.mp4

      - name: Run jest
        run: npx jest
